### ISSUE TITLE
convert current number alignment to a logic alignment

### ISSUE THREAD

**Issue by Laouen** [BoostGSoC18/Real#12]
Currently, numbers are aligned so we can operate with them by adding zeros at the beginning and end of the vector. 

The alignment should be logical using the number exponent to determine to which unit a digit belongs without modifying the number digit vector. When doing so, the number integer part should be generalized and we should be able to have precisions that do not consider the whole integer part as the worst precision

**Comment by sdavtaker** [comment]
It is important that the exponent is normalized. Meaning that the size of the digits coming from both numbers is the same so the logic displacement means the same. It may be worth to add a "digit_size" constant to the numeric classes.
